import { NgModule } from '@angular/core';
import { provideConfig } from '@spartacus/core';
import {
  ContentstackCmsFeatureModule,
  ContentstackConfig,
} from '@contentstack/contentstack-spartacus-connector';
import { contentstackDelivery } from '../../../../environments/contentstack.environment';

/**
 * Contentstack CMS feature (hybrid: SAP Commerce is the base for every page;
 * Contentstack overrides the slots you author). Generated by `ng add`.
 * Fill any <PLACEHOLDER> values in environments/contentstack.environment.ts, then import the Content
 * Model Starter Pack with the Contentstack CLI (csdx) — see GETTING_STARTED.md.
 *
 * The localeMapping and accessControl blocks below are scaffolded on purpose
 * (even at their defaults) so they're easy to find and turn on — a missing
 * localeMapping in particular is the usual cause of blank pages.
 */
@NgModule({
  imports: [ContentstackCmsFeatureModule],
  providers: [
    provideConfig(<ContentstackConfig>{
      contentstack: {
        // Delivery credentials live in environments/contentstack.environment.ts so secrets are not
        // committed inside this module.
        delivery: contentstackDelivery,
        cmsPageContentType: 'landing_page',
        occFallback: true,
        includeFallback: false,
        // Storefront language isocode -> the Contentstack locale your content is
        // authored in. IMPORTANT: with no matching entry the delivery query uses
        // the raw isocode (e.g. 'en'); if your stack has no such locale it returns
        // EMPTY content and pages render blank. These defaults match the starter
        // pack ('en-us' / 'de-de') — change them to your stack's locales.
        localeMapping: { en: 'en-us', de: 'de-de', ja: 'ja-jp', zh: 'zh-cn' },
        // Presentation-level content gating (show/hide entries by audience/role).
        // Off by default. To turn on: set enabled: true, tag entries in the
        // `access_tags` field, and provide CONTENTSTACK_CURRENT_USER so the
        // connector can read the signed-in user's roles. See CONTENT-MODEL.md.
        accessControl: { enabled: false },
        globalSlots: { contentType: 'global_slots' },
        componentContentType: 'cms_link_component',
        navTreeIncludeDepth: 2,
        pageTypeMapping: {
          CategoryPage: { contentTypeUid: 'category_page', sharedSlug: '/category' },
          ProductPage: { contentTypeUid: 'product_page', sharedSlug: '/product' },
        },
      },
    }),
  ],
})
export class ContentstackFeatureModule {}
